# Validate the file using e.g.
# https://rhysd.github.io/actionlint/

# There *could* be a point to be made that
# this workflow could be divided in two, cf.
# https://stackoverflow.com/q/69316044
# for instance (one to build, one to deploy).
# However, since we will always build and
# deploy, and since it introduces additional
# complications (detailed below), we prefer to
# keep the jobs in the same workflow.

name: Build & deploy (no fetch) (test)

permissions:
  contents: write
  pages: write
  id-token: write

on: 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: chetan/git-restore-mtime-action@v2
    - name: Cache  üíæ
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          pandoc-3.2.1-1-amd64.deb
        key: ${{ runner.os }}-pip-
        restore-keys: ${{ runner.os }}-pip-
    - name: Setup Python üêç
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Setup pandoc ‚öôÔ∏è
      run: |
        test -f pandoc-3.2.1-1-amd64.deb || wget https://github.com/jgm/pandoc/releases/download/3.2.1/pandoc-3.2.1-1-amd64.deb
        sudo dpkg -i pandoc-3.2.1-1-amd64.deb
        sudo apt-get install -y  texlive-xetex lmodern librsvg2-bin fonts-symbola
        pip install Pygments pandoc-include
    - name: Build üèóÔ∏è
      run: |
        cd /home/runner/work/princomp.github.io/princomp.github.io/source/
        make all
 
